<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DeepSigma.LogicEngine.Recipes</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DeepSigma.LogicEngine\DeepSigma.LogicEngine.csproj" />
  </ItemGroup>
</Project>
